### ISSUE TITLE
name is undefined in parse_child function

### ISSUE THREAD

**Issue by tinrobot2000** [htlcnn/civil3d_python_stubs#1]
Hi Long,
I noticed that the parse_child function has an undefined variable 'name', I have this working using 'child' 
https://github.com/htlcnn/civil3d_python_stubs/blob/2157eb188b2e5e4c5d2ae04af0ab84bff0ee3fd8/generate_civil3d_stubs.py#L337
Cheers
Mike

**Comment by htlcnn** [comment]
Thanks @tinrobot2000
